### ISSUE TITLE
Cleanup - Misc cleanup

### ISSUE THREAD

**Issue by Responseless** [BassT23/Proxmox#74] opened 2023-06-21 00:29 UTC
Just a few little cleanup issues and typos.

1. When running 'update --up' commands the text states 'The default action is to keep your current version' which is a bit confusing, maybe should say something like 'The default action is to backup your current config and use new config' ?

2. you type 'enything' instead of 'anything' ;)

3. When updating proxmox hosts with this script I see the error "dpkg-reconfigure: unable to re-open stdin: No file or directory" but when running manually outside of the script I don't. Still updates fine but just shows.

**Comment by BassT23** [comment] 2023-06-21 05:33
thanks for your inspiration ;)

Point 1 and 2 - is fixed in latest development version.

Point 3 - I don't want to fix for now. The problem is; If I fix a dpkg failure, its a deep system change, that could end in an total crash. So I desided to not fix this within the script.
It's better for the user to do that themselves.

**Closed** 2023-06-24 10:48 UTC
Labels: Resolved
